### ISSUE TITLE
Docs: Clarify details about this plugin

### ISSUE THREAD

**Issue by ghost** [eslint/json#19]
### What documentation issue do you want to solve?

I have doubts about your plugin after reading the blog post where you announced it:

1. Is @eslint/json planned to be a replacement to json plugins, such as eslint-plugin-json or eslint-plugin-jsonc?
2. Do you advise to keep using them together with your plugin at the same time?
3. Are you going to provide more rules to @eslint/json? What type of rules? (only those detached from the core ESLint that already existed or not)
4. In what page of your website can we read the table of rules and see examples for each rule? In the same way that ESLint provides a table for JavaScript rules.

### What do you think is the correct solution?

To announce in the documentation or in readme.md how this plugin compares to existing plugins focused on json.

To have a page in the website focused on this plugin and its rules.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
To answer your questions:

1. Yes, this is intended to replace those plugins.
2. I don't advise using them together. They take very different approaches to linting JSON. Many of the rules in these plugins are required because they are still going through the JavaScript linting functionality and those rules prevent invalid JSON from being created. This plugin uses a true JSON/JSONC/JSON5 parser that automatically handles a lot of that for you.
3. Yes, we will add more rules as we go. Please feel free to suggest new ones.
4. We don't have a website. The rules are listed on the [README](https://github.com/eslint/json?tab=readme-ov-file#rules).

I can add a FAQ in the README to answer some of these questions.
