### ISSUE TITLE
New Rule: package-json-sorted-keys / package-json-key-order

### ISSUE THREAD

**Issue by kachkaev** [eslint/json#37]
### Rule details

The rule would normalize `package.json` keys by following a convention in [sort-package-json](https://github.com/keithamus/sort-package-json) (or similar).

### What type of rule is this?

Suggests an alternate way of doing something

### Example code

```json
{
  "dependencies": {
    "sort-package-json": "1.0.0",
    "sort-object-keys": "1.0.0"
  },
  "version": "1.0.0",
  "name": "my-awesome-project"
}
```
↓
```json
{
  "name": "my-awesome-project",
  "version": "1.0.0",
  "dependencies": {
    "sort-object-keys": "1.0.0",
    "sort-package-json": "1.0.0"
  }
}
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.

### Additional comments

I am using [`sort-package-json`](https://github.com/keithamus/sort-package-json) via [`prettier-plugin-packagejson`](https://github.com/matzkoh/prettier-plugin-packagejson) and it works well. Automatic key sorting is especially useful in monorepos with lots of `package.json` files and contributors. The problem with `prettier-plugin-packagejson` is that it goes [outside the scope of Prettier](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about):

> **What Prettier is not concerned about**
> Prettier only prints code. It does not transform it. This is to limit the scope of Prettier. Let’s focus on the printing and do it really well!
> Here are a few examples of things that are out of scope for Prettier:
> - ...
> - Sorting/moving imports, object keys, class members, JSX keys, CSS properties or anything else. Apart from being a transform rather than just printing (as mentioned above), sorting is potentially unsafe because of side effects (for imports, as an example) and makes it difficult to verify the most important [correctness](https://prettier.io/docs/en/rationale.html#correctness) goal.

Now that ESLint supports JSON parsing, it’d be great to achieve the value of `sort-package-json` via a rule. Conceptually it is similar to sorting imports in JS files, so I believe that it fits the scope. WDYT?

---

**UPD** Maybe this should be done elsewhere because the rule would be `package.json` specific. There is a discussion in https://github.com/keithamus/sort-package-json/issues/322.

**Comment by kachkaev** [comment]
Prior art: https://github.com/kellyselden/eslint-plugin-json-files → `[json-files/sort-package-json](https://github.com/kellyselden/eslint-plugin-json-files/blob/main/docs/rules/sort-package-json.md)`

**Comment by fasttime** [comment]
Thanks for the suggestion @kachkaev, this sounds like an interesting rule. My feeling is that such a rule would not fit well in the standard ESLint JSON plugin, because its usage is limited to Node.js. For reference, other built-in Node.js-specific rules like [`no-process-exit`](https://eslint.org/docs/latest/rules/no-process-exit) were deprecated in ESLint v7 and replaced by equivalent rules in [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n). To my knowledge, `eslint-plugin-n` only supports JavaScript rules, although that could change in the future. So my recommendation is to leave this rule for a userland ESLint plugin for the time being as you suggested in the other discussion.

Any other thought about this suggestion @eslint/eslint-tsc? cc @eslint/eslint-community.

**Comment by bmeck** [comment]
Just leaving this here but not really having much to add. This would need to be a bit careful as well since sorting can affect some keys like `imports` and `exports` etc.

**Comment by nzakas** [comment]
This plugin is focused on generic JSON linting. As such, `package.json`-specific rules are out of scope.

However, as with ESLint rules in general,  you can always create your own plugin with any rule that you want.
